# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: yarn test

      # runt deploy
      # - run: ssh-keyscan dlei.ca >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "7a:a0:8a:92:90:c8:00:5c:c9:14:3e:f3:1b:b9:2f:05"
      - run: |
          pwd
          ls ~/.ssh -l
          ssh-keyscan dlei.ca >> ~/.ssh/known_hosts
          ssh-copy-id root@dlei.ca
      # - run:
      #     command: |
      #       # ssh-keygen -t rsa
      #       pwd
      #       scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./.ssh/id_rsa.pub root@dlei.ca:./
      - deploy:
          name: Deploy Over SSH
          command: |
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./www/index.html root@dlei.ca:/root